"use client";
import Image from "next/image";
import { useEffect, useState } from "react";
import { CartDrawer, type CartItem } from "@/components/cart/CartDrawer";
import { LeadCaptureDialog } from "@/components/leads/LeadCaptureDialog";
import { ProductGrid } from "@/components/catalog/ProductGrid";
import { products, type Product } from "@/lib/catalog";
import { WhatsappIcon } from "@/components/whatsapp/WhatsappIcon";

const WA = "595982029217";
const whatsapp = (message: string) => `https://wa.me/${WA}?text=${encodeURIComponent(message)}`;
const services = [
  ["01", "Stands para eventos", "Planificación y construcción de espacios que hacen visible tu marca.", "Diseñamos →"],
  ["02", "Activaciones de marca", "Experiencias con tecnología, interacción y soporte en cada detalle.", "Activamos →"],
  ["03", "Coberturas digitales", "Videos, reels y tomas aéreas con drone para que el evento continúe online.", "Cubrimos →"]
];
const steps = [["01", "Contanos tu idea", "Fecha, lugar, objetivo y todo lo que imaginás para tu evento."], ["02", "Armamos la propuesta", "Combinamos equipos, servicios y un plan a medida."], ["03", "Instalamos y probamos", "Nuestro equipo deja todo listo antes de que empiece el evento."], ["04", "Te acompañamos", "Soporte técnico durante la experiencia y retiro coordinado."]];
const reasons = [["◈", "Equipos propios", "Disponibilidad y control sobre cada equipo que alquilás."], ["⌁", "Soporte incluido", "Instalación, operación y asistencia técnica en el evento."], ["✦", "Experiencia real", "Más de 10 años creando experiencias para marcas."], ["↗", "Todo Paraguay", "Llegamos donde tu evento necesita impacto visual."]];

export default function HomePage() {
  const [cart, setCart] = useState<CartItem[]>([]);
  const [leadOpen, setLeadOpen] = useState(false);
  const [navScrolled, setNavScrolled] = useState(false);
  const [stickyClosed, setStickyClosed] = useState(false);

  useEffect(() => { const onScroll = () => setNavScrolled(window.scrollY > 40); window.addEventListener("scroll", onScroll, { passive: true }); return () => window.removeEventListener("scroll", onScroll); }, []);
  const addProduct = (product: Product) => { setCart(current => { const existing = current.find(item => item.product.id === product.id); return existing ? current.map(item => item.product.id === product.id ? { ...item, quantity: item.quantity + 1 } : item) : [...current, { product, quantity: 1, duration: 1 }]; }); setLeadOpen(true); };
  const openLead = () => setLeadOpen(true);
  const productStructuredData = products.map(product => ({ "@type": "Product", name: product.name, description: product.description, image: `https://ledbox.online${product.image}`, brand: { "@type": "Brand", name: "LedBox Paraguay" }, offers: { "@type": "Offer", priceCurrency: "PYG", price: product.price, availability: "https://schema.org/InStock", url: "https://ledbox.online/#productos", priceSpecification: { "@type": "UnitPriceSpecification", priceCurrency: "PYG", price: product.price, unitText: product.unitLabel } } }));
  const businessStructuredData = { "@context": "https://schema.org", "@graph": [{ "@type": "LocalBusiness", name: "LedBox Paraguay", description: "Alquiler de pantallas LED, tótems, kioskos touch y soluciones visuales para eventos.", url: "https://ledbox.online/", telephone: "+595982029217", areaServed: { "@type": "Country", name: "Paraguay" }, sameAs: ["https://www.instagram.com/ledboxpy/"] }, ...productStructuredData] };
  return <>
    <div className="led-grid-bg" aria-hidden="true" />
    <nav id="nav" className={navScrolled ? "scrolled" : ""} aria-label="Navegación principal">
      <a href="#hero" className="logo-link" aria-label="LedBox, volver al inicio"><Image className="logo-img" src="/assets/icon-192.png" alt="LedBox" width={192} height={192} priority /></a>
      <div className="nav-center"><a href="#productos">Productos</a><a href="#servicios">Servicios</a><a href="#marcas">Marcas</a><a href="#proceso">Proceso</a><a href="#contacto">Contacto</a></div>
      <a href={whatsapp("Hola LedBox! Quiero consultar disponibilidad.")} target="_blank" rel="noopener noreferrer" className="nav-cta">Consultar →</a>
    </nav>

    <main>
      <header id="hero">
        <div><div className="hero-kicker rise on">LedBox Paraguay · Alquileres & Eventos</div><h1 className="mega rise on">Tecnología<br /><span className="led glow">visual</span> que<br />impulsa tu marca</h1><p className="hero-sub rise on">Alquiler de <strong>pantallas LED, iPoster, tótems y kioskos touch</strong>. Planificación y construcción de <strong>stands</strong> para eventos nacionales e internacionales. Coberturas digitales: <strong>videos, reels y tomas aéreas con drone</strong>.</p><div className="hero-actions rise on"><button className="btn-led" type="button" onClick={openLead}>Consultar disponibilidad</button><a href="#productos" className="btn-line">Ver productos</a></div></div>
        <div className="hero-foot"><span><b>Alquileres</b> en todo Paraguay</span><span><b>Eventos</b> nacionales e internacionales</span><span><b>Instalación + soporte</b> incluidos</span></div>
      </header>
      <div className="ticker" aria-hidden="true"><div className="ticker-track"><span>Pantallas LED ● iPoster ● Tótem Touch ● Kiosko Touch ● Stands ● Activaciones ● Coberturas Digitales ● </span><span>Pantallas LED ● iPoster ● Tótem Touch ● Kiosko Touch ● Stands ● Activaciones ● Coberturas Digitales ● </span></div></div>
      <section id="stats" aria-label="LedBox en números"><div className="stat rise"><div className="n">+10<em>+</em></div><div className="l">Años de experiencia en eventos</div></div><div className="stat rise"><div className="n">+100<em>+</em></div><div className="l">Expoferias cubiertas</div></div><div className="stat rise"><div className="n">PY<em>+</em></div><div className="l">Cobertura nacional e internacional</div></div><a className="stat rise stat-social" href="https://www.instagram.com/ledboxpy/" target="_blank" rel="noopener noreferrer"><div className="n"><InstagramIcon /> <em>@ledboxpy</em></div><div className="l">Seguinos en Instagram →</div></a></section>

      <section id="productos" aria-labelledby="products-title"><div className="sec-head"><div><div className="sec-kicker">Alquiler de equipos</div><h2 id="products-title" className="sec-title rise">Productos<span className="led">.</span></h2></div><p className="sec-desc rise">Equipos propios, <strong>instalación y soporte técnico incluidos</strong>. Consultá disponibilidad para la fecha de tu evento.</p></div><p className="catalog-note">Precios de lista orientativos. El valor final puede variar según la cantidad de días, la cantidad y combinación de equipos, instalación, traslado y necesidades del evento. Podemos armar combos a medida.</p><ProductGrid onAdd={addProduct} /></section>
      <section id="servicios" aria-labelledby="services-title"><div className="sec-head"><div><div className="sec-kicker">Más que equipos</div><h2 id="services-title" className="sec-title rise">Servicios<span className="led">.</span></h2></div><p className="sec-desc rise">Una experiencia visual completa, desde la primera idea hasta el último minuto de tu evento.</p></div>{services.map(([num,title,desc,cta]) => <a className="svc rise" href="#contacto" key={num}><span className="num">{num}</span><h3>{title}</h3><p>{desc}</p><span className="go">{cta}</span></a>)}</section>
      <section id="marcas" aria-labelledby="brands-title"><div className="sr-only" id="brands-title">Marcas que confiaron en LedBox</div><div className="brands-track" aria-hidden="true">{["Tigo", "Personal", "Bancard", "Cervepar", "Coca-Cola", "Pilsen", "Banco Atlas", "Claro", "ueno", "Shopping del Sol", "Tigo", "Personal", "Bancard"].map((brand, i) => <span className="brand" key={`${brand}-${i}`}>{brand}</span>)}</div><p className="marcas-note">Marcas que ya hicieron visible su próximo evento · <a href="#contacto">La próxima puede ser la tuya →</a></p></section>
      <section id="proceso" aria-labelledby="process-title"><div className="sec-head"><div><div className="sec-kicker">Así trabajamos</div><h2 id="process-title" className="sec-title rise">Proceso<span className="led">.</span></h2></div><p className="sec-desc rise">Simple para vos. Preciso para nosotros. Sin sorpresas el día del evento.</p></div><div className="steps">{steps.map(([num,title,desc]) => <div className="stp rise" key={num}><div className="n">{num}</div><h3>{title}</h3><p>{desc}</p></div>)}</div></section>
      <section id="porque" aria-labelledby="why-title"><div className="sec-head"><div><div className="sec-kicker">Por qué LedBox</div><h2 id="why-title" className="sec-title rise">Hecho para<br /><span className="led">impactar.</span></h2></div><p className="sec-desc rise">La tecnología es el medio. Tu marca es la protagonista.</p></div><div className="why-grid">{reasons.map(([icon,title,desc]) => <div className="why rise" key={title}><div className="ico" aria-hidden="true">{icon}</div><h4>{title}</h4><p>{desc}</p></div>)}</div></section>
      <section id="contacto" aria-labelledby="contact-title"><div className="c-left"><div><div className="sec-kicker">Hablemos</div><h2 id="contact-title" className="c-title rise">Tu evento.<br /><span className="led">En grande.</span></h2><p className="c-desc">Contanos qué estás preparando y armamos una propuesta a la medida de tu evento.</p></div><div className="c-meta"><a href={whatsapp("Hola LedBox! Quiero consultar disponibilidad.")} target="_blank" rel="noopener noreferrer"><b>WhatsApp:</b> +595 982 029 217 →</a><a href="https://www.instagram.com/ledboxpy/" target="_blank" rel="noopener noreferrer"><b>Instagram:</b> @ledboxpy</a><span><b>Santiago J. Rodas</b> · Gerente</span><span>Asunción · Alquileres en todo Paraguay 🇵🇾</span></div></div><div className="c-right rise"><p className="chips-title">Consultas rápidas — un toque y te ayudamos</p><div className="chips"><button className="chip" type="button" onClick={openLead}>▣ Pantalla LED →</button><button className="chip" type="button" onClick={openLead}>◫ Tótem / Kiosko Touch →</button><button className="chip" type="button" onClick={openLead}>⌂ Stand para evento →</button><button className="chip" type="button" onClick={openLead}>🎥 Cobertura digital →</button></div><button className="btn-led" type="button" onClick={openLead}>Solicitar cotización →</button><p className="f-note contact-note">Te pedimos solo los datos necesarios para responderte y preparar tu cotización.</p></div></section>
    </main>

    <footer><div className="ft-top"><a href="#hero" className="logo-link" aria-label="LedBox, volver al inicio"><Image className="logo-img" src="/assets/icon-192.png" alt="LedBox" width={192} height={192} /></a><div className="ft-links"><a href="#productos">Productos</a><a href="#servicios">Servicios</a><a href="#proceso">Proceso</a><a href="#contacto">Contacto</a><a href="https://www.instagram.com/ledboxpy/" target="_blank" rel="noopener noreferrer">Instagram</a></div></div><a className="ft-social" href="https://www.instagram.com/ledboxpy/" target="_blank" rel="noopener noreferrer" aria-label="Instagram @ledboxpy"><InstagramIcon /><span>Instagram · @ledboxpy</span></a><div className="ft-div" /><div className="ft-bottom"><span>© 2026 LedBox Paraguay · Todos los derechos reservados</span><span>Tecnología visual que impulsa tu marca</span><span>Asunción, Paraguay · ledbox.online</span></div><div className="ft-credit"><span>LedBox v2.0.0</span><span>Desarrollado por <a href="https://owncoding.dev" target="_blank" rel="noopener noreferrer">owncoding.dev</a></span></div><div className="ft-bg" aria-hidden="true">LEDBOX</div></footer>
    <CartDrawer items={cart} onChange={setCart} onQuote={openLead} />
    <a href={whatsapp("Hola LedBox! Quiero más información.")} target="_blank" rel="noopener noreferrer" className="wa-float" aria-label="Abrir WhatsApp"><WhatsappIcon size={28} /></a>
    {!stickyClosed && <div id="sticky-cta" role="complementary"><span className="txt">¿Evento a la vista? <strong>Consultá disponibilidad hoy</strong></span><button className="go-btn" type="button" onClick={openLead}>WhatsApp →</button><button className="x" type="button" onClick={() => setStickyClosed(true)} aria-label="Cerrar aviso">✕</button></div>}
    <LeadCaptureDialog open={leadOpen} items={cart} onClose={() => setLeadOpen(false)} />
    <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(businessStructuredData) }} />
  </>;
}
function InstagramIcon() { return <svg viewBox="0 0 24 24" fill="none" aria-hidden="true"><rect x="3" y="3" width="18" height="18" rx="5" stroke="currentColor" strokeWidth="1.8" /><circle cx="12" cy="12" r="4.2" stroke="currentColor" strokeWidth="1.8" /><circle cx="17.4" cy="6.7" r="1" fill="currentColor" /></svg>; }
