"use client";

import Link from "next/link";
import { useCallback, useEffect, useState } from "react";
import { useRouter } from "next/navigation";
import { AdminError, AdminFrame, AdminSpinner } from "./AdminFrame";

type Overview = { counts: Record<string, number>; finance: { totalReceivable: number; totalPayable: number; committedCash: number }; upcoming: Array<{ id: string; name: string; location: string | null; startsAt: string | null; status: string; client: { name: string; company: string | null }; assignments: Array<{ quantity: number; inventory: { name: string } }>; tasks: Array<{ title: string; completedAt: string | null }> }> };
type Client = { id: string; name: string; company: string | null; type: string; email: string | null; phone: string | null; ruc: string | null; _count: { events: number; budgets: number } };
type Event = { id: string; name: string; location: string | null; startsAt: string | null; status: string; client: Client };
type Resources = { suppliers: Array<{ id: string; name: string; category: string; phone: string | null }>; inventory: Array<{ id: string; name: string; category: string; kind: string; quantity: number; status: string }>; promoters: Array<{ id: string; name: string; phone: string | null; specialties: string | null }> };
type Budget = { id: string; title: string; status: string; total: number; costEstimate: number; client: Client; event: { name: string } | null; payments: Array<{ amount: number }> };
const money = (n: number) => new Intl.NumberFormat("es-PY", { style: "currency", currency: "PYG", maximumFractionDigits: 0 }).format(n);
const date = (v?: string | null) => v ? new Intl.DateTimeFormat("es-PY", { dateStyle: "medium", timeStyle: "short" }).format(new Date(v)) : "Fecha a confirmar";

export function AdminDashboard() {
  const router = useRouter();
  const [overview, setOverview] = useState<Overview | null>(null); const [clients, setClients] = useState<Client[]>([]); const [events, setEvents] = useState<Event[]>([]); const [budgets, setBudgets] = useState<Budget[]>([]); const [resources, setResources] = useState<Resources | null>(null); const [tab, setTab] = useState("overview"); const [loading, setLoading] = useState(true); const [error, setError] = useState(""); const [user, setUser] = useState<{ name: string } | null>(null);
  const load = useCallback(async () => { setLoading(true); setError(""); try { const session = await fetch("/api/admin/session", { cache: "no-store" }); if (session.status === 401) return router.replace("/admin/login"); setUser((await session.json()).user); const [o, c, e, b, r] = await Promise.all([fetch("/api/admin/overview"), fetch("/api/admin/clients"), fetch("/api/admin/events"), fetch("/api/admin/budgets"), fetch("/api/admin/resources")]); if ([o, c, e, b, r].some((x) => x.status === 401)) return router.replace("/admin/login"); setOverview(await o.json()); setClients((await c.json()).clients || []); setEvents((await e.json()).events || []); setBudgets((await b.json()).budgets || []); setResources(await r.json()); } catch { setError("No pudimos cargar el centro de operaciones."); } finally { setLoading(false); } }, [router]);
  useEffect(() => { void load(); }, [load]);
  async function logout() { await fetch("/api/auth/logout", { method: "POST" }); router.replace("/admin/login"); router.refresh(); }
  if (loading) return <AdminFrame><div className="admin-loading-panel"><AdminSpinner label="Cargando panel" /><span>Cargando centro de operaciones…</span></div></AdminFrame>;
  return <AdminFrame eyebrow="LedBox · Centro de operaciones"><div className="admin-dashboard"><header className="admin-dashboard-head"><div><span className="admin-card-index">Workspace / operaciones</span><h1 className="admin-title admin-title--dashboard">Todo bajo<br /><span>control.</span></h1><p className="admin-lede">{user ? `Hola, ${user.name}.` : "Panel privado"} Eventos, clientes, alquileres, costos y rentabilidad en un solo lugar.</p></div><div className="admin-dashboard-actions"><Link href="/" className="admin-ghost-button">Ver sitio ↗</Link><button className="admin-ghost-button" onClick={logout}>Cerrar sesión</button></div></header>{error && <AdminError message={error} />}<nav className="admin-tabs" aria-label="Módulos"><button className={tab === "overview" ? "active" : ""} onClick={() => setTab("overview")}>Resumen</button><button className={tab === "events" ? "active" : ""} onClick={() => setTab("events")}>Eventos</button><button className={tab === "clients" ? "active" : ""} onClick={() => setTab("clients")}>Clientes</button><button className={tab === "budgets" ? "active" : ""} onClick={() => setTab("budgets")}>Presupuestos</button><button className={tab === "resources" ? "active" : ""} onClick={() => setTab("resources")}>Inventario</button><button className={tab === "suppliers" ? "active" : ""} onClick={() => setTab("suppliers")}>Proveedores</button><button className={tab === "promoters" ? "active" : ""} onClick={() => setTab("promoters")}>Promotoras</button></nav>{tab === "overview" && <OverviewPanel overview={overview} events={events} />}{tab === "events" && <EventsPanel events={events} clients={clients} reload={load} />}{tab === "clients" && <ClientsPanel clients={clients} reload={load} />}{tab === "budgets" && <BudgetsPanel budgets={budgets} clients={clients} events={events} reload={load} />}{tab === "resources" && <ResourcesPanel resources={resources} />}{tab === "suppliers" && <SimpleResource title="Proveedores" rows={resources?.suppliers.map((x) => `${x.name} · ${x.category} · ${x.phone || "sin contacto"}`) || []} />}{tab === "promoters" && <SimpleResource title="Promotoras activas" rows={resources?.promoters.map((x) => `${x.name} · ${x.specialties || "perfil general"} · ${x.phone || "sin contacto"}`) || []} />}</div></AdminFrame>;
}
function OverviewPanel({ overview, events }: { overview: Overview | null; events: Event[] }) { if (!overview) return null; const c = overview.counts; return <><section className="admin-stats admin-stats--wide"><Stat label="Clientes activos" value={c.clients} note="finales y revendedores" /><Stat label="Eventos" value={c.events} note="operación completa" /><Stat label="Por cobrar" value={money(overview.finance.totalReceivable)} note="ventas aprobadas" /><Stat label="Por pagar" value={money(overview.finance.totalPayable)} note="proveedores comprometidos" /></section><section className="admin-module-grid"><div className="admin-module"><span className="admin-card-index">Esta semana</span><h2>Próximos eventos</h2>{events.slice(0, 5).map((e) => <div className="admin-event-mini" key={e.id}><strong>{e.name}</strong><span>{e.client.company || e.client.name} · {date(e.startsAt)}</span><small>{e.location || "Ubicación a confirmar"} · {e.status}</small></div>)}{events.length === 0 && <p className="admin-muted">No hay eventos cargados todavía.</p>}</div><div className="admin-module"><span className="admin-card-index">Pipeline</span><h2>Qué mirar hoy</h2><div className="admin-check-row"><b>{c.leads}</b><span>leads nuevos por contactar</span></div><div className="admin-check-row"><b>{c.budgets}</b><span>presupuestos activos</span></div><div className="admin-check-row"><b>{c.inventory}</b><span>ítems de inventario controlados</span></div><div className="admin-check-row"><b>{c.suppliers}</b><span>proveedores disponibles</span></div></div></section></>; }
function Stat({ label, value, note }: { label: string; value: string | number; note: string }) { return <div className="admin-stat"><span>{label}</span><strong>{value}</strong><small>{note}</small></div>; }
function EventsPanel({ events, clients, reload }: { events: Event[]; clients: Client[]; reload: () => void }) { const [form, setForm] = useState({ clientId: "", name: "", location: "", startsAt: "" }); const [saving, setSaving] = useState(false); async function submit(e: React.FormEvent) { e.preventDefault(); setSaving(true); await fetch("/api/admin/events", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify(form) }); setForm({ clientId: "", name: "", location: "", startsAt: "" }); setSaving(false); reload(); } return <Module title="Eventos y calendario" subtitle="Montaje · evento · desmontaje · checklist"><form className="admin-quick-form" onSubmit={submit}><select required value={form.clientId} onChange={(e) => setForm({ ...form, clientId: e.target.value })}><option value="">Cliente…</option>{clients.map((c) => <option key={c.id} value={c.id}>{c.company || c.name}</option>)}</select><input required placeholder="Nombre del evento" value={form.name} onChange={(e) => setForm({ ...form, name: e.target.value })} /><input placeholder="Lugar" value={form.location} onChange={(e) => setForm({ ...form, location: e.target.value })} /><input type="datetime-local" value={form.startsAt} onChange={(e) => setForm({ ...form, startsAt: e.target.value })} /><button className="btn-led" disabled={saving}>{saving ? "Guardando…" : "Agregar evento"}</button></form><div className="admin-table">{events.map((e) => <div className="admin-table-row" key={e.id}><strong>{e.name}</strong><span>{e.client.company || e.client.name}</span><span>{date(e.startsAt)}</span><span>{e.location || "Sin lugar"}</span><b>{e.status}</b></div>)}</div></Module>; }
function ClientsPanel({ clients, reload }: { clients: Client[]; reload: () => void }) { const [form, setForm] = useState({ name: "", company: "", type: "FINAL", phone: "", email: "", ruc: "" }); async function submit(e: React.FormEvent) { e.preventDefault(); await fetch("/api/admin/clients", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify(form) }); setForm({ name: "", company: "", type: "FINAL", phone: "", email: "", ruc: "" }); reload(); } return <Module title="Clientes y oportunidades" subtitle="Clientes finales · mayoristas · revendedores"><form className="admin-quick-form" onSubmit={submit}><input required placeholder="Nombre / responsable" value={form.name} onChange={(e) => setForm({ ...form, name: e.target.value })} /><input placeholder="Empresa" value={form.company} onChange={(e) => setForm({ ...form, company: e.target.value })} /><select value={form.type} onChange={(e) => setForm({ ...form, type: e.target.value })}><option value="FINAL">Cliente final</option><option value="RESELLER">Mayorista / revendedor</option></select><input placeholder="Teléfono" value={form.phone} onChange={(e) => setForm({ ...form, phone: e.target.value })} /><input placeholder="Email" type="email" value={form.email} onChange={(e) => setForm({ ...form, email: e.target.value })} /><input placeholder="RUC" value={form.ruc} onChange={(e) => setForm({ ...form, ruc: e.target.value })} /><button className="btn-led">Registrar cliente</button></form><div className="admin-table">{clients.map((c) => <div className="admin-table-row" key={c.id}><strong>{c.company || c.name}</strong><span>{c.type === "RESELLER" ? "Revendedor" : "Final"}</span><span>{c.phone || "Sin teléfono"}</span><span>{c._count.events} eventos · {c._count.budgets} presupuestos</span></div>)}</div></Module>; }
function BudgetsPanel({ budgets, clients, events, reload }: { budgets: Budget[]; clients: Client[]; events: Event[]; reload: () => void }) { const [form, setForm] = useState({ clientId: "", eventId: "", title: "", item: "", quantity: "1", days: "1", unitPrice: "" }); const [saving, setSaving] = useState(false); async function submit(e: React.FormEvent) { e.preventDefault(); setSaving(true); await fetch("/api/admin/budgets", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ clientId: form.clientId, eventId: form.eventId || undefined, title: form.title, items: [{ name: form.item || form.title, quantity: Number(form.quantity), days: Number(form.days), unitPrice: Number(form.unitPrice) }] }) }); setForm({ clientId: "", eventId: "", title: "", item: "", quantity: "1", days: "1", unitPrice: "" }); setSaving(false); reload(); } return <Module title="Presupuestos y rentabilidad" subtitle="Venta · costo estimado · margen · pagos recibidos"><form className="admin-quick-form" onSubmit={submit}><select required value={form.clientId} onChange={(e) => setForm({ ...form, clientId: e.target.value })}><option value="">Cliente…</option>{clients.map((c) => <option key={c.id} value={c.id}>{c.company || c.name}</option>)}</select><select value={form.eventId} onChange={(e) => setForm({ ...form, eventId: e.target.value })}><option value="">Evento opcional…</option>{events.map((e) => <option key={e.id} value={e.id}>{e.name}</option>)}</select><input required placeholder="Título del presupuesto" value={form.title} onChange={(e) => setForm({ ...form, title: e.target.value })} /><input required placeholder="Producto / servicio" value={form.item} onChange={(e) => setForm({ ...form, item: e.target.value })} /><input required type="number" min="1" placeholder="Cantidad" value={form.quantity} onChange={(e) => setForm({ ...form, quantity: e.target.value })} /><input required type="number" min="1" placeholder="Días" value={form.days} onChange={(e) => setForm({ ...form, days: e.target.value })} /><input required type="number" min="0" placeholder="Precio unitario" value={form.unitPrice} onChange={(e) => setForm({ ...form, unitPrice: e.target.value })} /><button className="btn-led" disabled={saving}>{saving ? "Guardando…" : "Crear presupuesto"}</button></form><div className="admin-table">{budgets.map((b) => { const paid = b.payments.reduce((sum, p) => sum + p.amount, 0); return <div className="admin-table-row" key={b.id}><strong>{b.title}</strong><span>{b.client.company || b.client.name}</span><span>{b.event?.name || "Sin evento"}</span><span>{money(b.total)} · cobrado {money(paid)}</span><b>{b.status}</b></div>; })}{budgets.length === 0 && <p className="admin-muted">Todavía no hay presupuestos.</p>}</div></Module>; }
function ResourcesPanel({ resources }: { resources: Resources | null }) { return <Module title="Inventario y equipos" subtitle="Reutilizable · consumible · descartable · disponibilidad"><div className="admin-table">{resources?.inventory.map((x) => <div className="admin-table-row" key={x.id}><strong>{x.name}</strong><span>{x.category}</span><span>{x.kind}</span><span>cantidad: {x.quantity}</span><b>{x.status}</b></div>)}</div></Module>; }
function SimpleResource({ title, rows }: { title: string; rows: string[] }) { return <Module title={title} subtitle="Base operativa LEDBOX"><div className="admin-table">{rows.map((row) => <div className="admin-table-row" key={row}><strong>{row}</strong></div>)}{rows.length === 0 && <p className="admin-muted">Todavía no hay registros.</p>}</div></Module>; }
function Module({ title, subtitle, children }: { title: string; subtitle: string; children: React.ReactNode }) { return <section className="admin-module admin-module--full"><span className="admin-card-index">Módulo / gestión</span><h2>{title}</h2><p className="admin-muted">{subtitle}</p>{children}</section>; }
